language: node_js
node_js:
  - '0.10'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower
  - bower install
script: npm run ci-test
after_script: cat ./coverage/PhantomJS*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
env:
  global:
    - secure: UOggtjPHrdjMh02+R7dFUpq1RWEideb8x3Qise4DLEgMLGAIuZEQsKgJ/d1gFdL0K4pdlU/7l9F03EXNi4KtOkdDtEmbFBqXPRHXZhB5Dhoo1xAz0MGcQSOU9eb19Ds02TS5gioW/jSbm/x+r2Knmq199g3M4k9Eu+ZyuMN2Qh0=
    - secure: Mv/8hRcMOE6CHBuLDI0R7ihHmrahg+9qWbA7F7qy+f5n9yrNOH85YOJzo8J+qHHG5lJeJj103iUjKzkt0lSw44GLWBpaEt1jMbY/LkmB0PzBoKCi8E5tCUijyY7VFiwu6WUP8Y936NLMPAPD7e95NgXVaclrsCF0vv4uV1oNGJI=
    - secure: k+oHekpuiok4e/TeFlSRwk20tbpa/7dWrODOQUSB/V682QKRuVCyr9pSZKD7SRO3LxTHfBQLaTlM01qyAuqreAK7otTctP1tIE7il/DLJoaTa5OTv2TXtjFvsjEg4zNzTLM7jmlEB+gwV2FslHKvFDRD83dlH5CIq1CCv2SEpLE=
    - secure: JE02AsJ9K5SrUvpi03ahq/TCBH7ViX4/cRCveQ1b4ciBJN3F1VHjdnAechk2WQ5iSa1NhIOmI39QAu61c263WCyhw47ZZjtGMKNmAf/AneD3pJfudvR0Bb/cinYn2Kvp8qvHg9m1xzbAmZbzXrXnqljUvhaQZ4ogYvkYTe7bCU0=
