language: node_js
node_js:
  - '0.10'
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  global:
    - secure: UOggtjPHrdjMh02+R7dFUpq1RWEideb8x3Qise4DLEgMLGAIuZEQsKgJ/d1gFdL0K4pdlU/7l9F03EXNi4KtOkdDtEmbFBqXPRHXZhB5Dhoo1xAz0MGcQSOU9eb19Ds02TS5gioW/jSbm/x+r2Knmq199g3M4k9Eu+ZyuMN2Qh0=
    - secure: Mv/8hRcMOE6CHBuLDI0R7ihHmrahg+9qWbA7F7qy+f5n9yrNOH85YOJzo8J+qHHG5lJeJj103iUjKzkt0lSw44GLWBpaEt1jMbY/LkmB0PzBoKCi8E5tCUijyY7VFiwu6WUP8Y936NLMPAPD7e95NgXVaclrsCF0vv4uV1oNGJI=
